version: "3"

services:
  database-ride:
    container_name: database-ride
    image: postgres:16.3-alpine
    ports:
      - 5432:5432
    expose:
      - 5432
    restart: always
    env_file:
      - .env
    environment:
      DATABASE: ${DATABASE}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
      - ./create.sql:/docker-entrypoint-initdb.d/0_init.sql
    
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
